name: app_cliente_protocolo_mob_ser
description: A new Flutter project.
publish_to: 'none' 
version: 0.0.0-alpha.1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  dependencies_module:
    path: ../modulos/dependencies_module

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
